### ISSUE TITLE
batch processing and documentation

### ISSUE THREAD

**Issue by bruceravel** [NSLS-II/N2SNUserTools#4]
Hi,  here is my laundry list of gripes after 15 minutes of managing users at BMM.

1. There does not seem to be a way to add or remove users in bulk.  With PIs and students, I had 14 users from the last week to manage. That was a lot of typing and retyping my password
2. Where are the user statuses explained?  What exactly does USER, GUACCRTL, and GUACVIEW allow a user to do? 
3. It seems that `n2sn_remove_user` should actually be called `n2sn_remove_privilege`.  Removing with RIGHT=GUACVIEW does not remove the user, it seems to only reduce their privilege.
4. I don't think a readthedocs page is necessary (although it would be swell) ... even a terse README could cover a lot of these issues.  Code diving is a bit of a deep dive in that familiarity with the tools behind n2sntools is needed to figure out answers to some of these questions.
5. Where does the STAFF list come from?  How does a person get added to the STAFF list.  (We have a new staff member at BMM.)

**Comment by ambarb** [comment]
For batch processing, can we also do the same for `user`, `quacctrl`, and `quacview`?  Even `all` would be okay so I don't have to retype my password 3 times per user with multiple privileges because I have to remove each privilege one at a time.

**Comment by mrakitin** [comment]
Closing in favor of https://jira.nsls2.bnl.gov/projects/N2SNUT/issues/N2SNUT-2.
