### ISSUE TITLE
ENH add bash hints

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/N2SNUserTools#5]
I see that commands have `-h` option which is great.  But I don't want to rely on the docs to refresh my memory (or to get one started) so some extra bash tools would be great.  I can offer two suggestions, but maybe you have a better idea, which is great too.

-  tab complete on commands. if there is not a unique option, then all options are printed to screen (like with directories or filenames)

- `n2ns` that just prints all the commands?  Then you can pick your favorite and add -h to figure out how to use it.   Kinda like how  `manage-iocs` gives you hints.  If you type just this into bash,  all the  next possible options are printed to screen.

**Comment by mrakitin** [comment]
Closing in favor of https://jira.nsls2.bnl.gov/browse/N2SNUT-3.
